SELECT car.CAR_ID, car.CAR_TYPE, floor(car.DAILY_FEE * 0.3 * (100 - p.DISCOUNT_RATE)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR car
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
        ON car.CAR_TYPE = p.CAR_TYPE AND p.DURATION_TYPE = '30일 이상'
WHERE car.CAR_TYPE IN ('SUV', '세단')
    AND NOT EXISTS (
        SELECT *
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
        WHERE
            car.CAR_ID = h.CAR_ID AND
            (h.START_DATE <= '2022-11-30' AND h.END_DATE >= '2022-11-01')
    )
    AND car.DAILY_FEE * 0.3 * (100 - p.DISCOUNT_RATE) >= 500000
    AND car.DAILY_FEE * 0.3 * (100 - p.DISCOUNT_RATE) < 2000000
ORDER BY FEE DESC, car.CAR_TYPE ASC, car.CAR_ID DESC;