-- 코드를 작성해주세요
WITH total_count AS (
    SELECT COUNT(*) AS cnt FROM ECOLI_DATA
)
SELECT
    ID,
    CASE
        WHEN COUNT(*) OVER(ORDER BY SIZE_OF_COLONY) <= cnt / 4 THEN 'LOW'
        WHEN COUNT(*) OVER(ORDER BY SIZE_OF_COLONY) <= cnt / 2 THEN 'MEDIUM'
        WHEN COUNT(*) OVER(ORDER BY SIZE_OF_COLONY) <= cnt * 3 / 4 THEN 'HIGH'
        ELSE 'CRITICAL'
    END AS COLONY_NAME
FROM ECOLI_DATA, total_count
ORDER BY ID;