SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM (
    SELECT MAX(LENGTH) AS LENGTH, FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) MAX_FISH
    INNER JOIN FISH_INFO FI ON MAX_FISH.FISH_TYPE = FI.FISH_TYPE AND MAX_FISH.LENGTH = FI.LENGTH
    INNER JOIN FISH_NAME_INFO FNI ON MAX_FISH.FISH_TYPE = FNI.FISH_TYPE
ORDER BY FI.ID;
