SELECT SCORE, e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM HR_EMPLOYEES e
    JOIN (
        SELECT
            EMP_NO,
            SUM(SCORE) AS SCORE,
            rank() over (ORDER BY SUM(SCORE) DESC) AS RANKING
        FROM HR_GRADE
        GROUP BY EMP_NO
    ) g ON e.EMP_NO = g.EMP_NO
WHERE RANKING = 1;